//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiVer1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BorrowingRequest
    {
        public long Id { get; set; }
        public long RequestUserId { get; set; }
        public long ItemId { get; set; }
        public string RequestType { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int StatusId { get; set; }
        public int LibraryId { get; set; }
        public Nullable<long> ApprovedByUserId { get; set; }
        public Nullable<System.DateTime> ApprovedDateTime { get; set; }
        public long CreatedByUserId { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public Nullable<long> LastModifiedByUserId { get; set; }
        public Nullable<System.DateTime> LastModifiedDateTime { get; set; }
        public bool IsActive { get; set; }
    }
}
