//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiVer1
{
    using System;
    using System.Collections.Generic;
    
    public partial class JoinningRequest
    {
        public long Id { get; set; }
        public long UserId { get; set; }
        public int LibraryId { get; set; }
        public int StatusId { get; set; }
        public Nullable<System.DateTime> SubmittedDateTime { get; set; }
        public Nullable<System.DateTime> ApprovedDateTime { get; set; }
        public Nullable<long> ApprovedUserId { get; set; }
    }
}
