//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiVer1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transfer
    {
        public long Id { get; set; }
        public long TransferFromUserId { get; set; }
        public long TransferToUserId { get; set; }
        public long ItemId { get; set; }
        public int LibraryId { get; set; }
        public string TransferType { get; set; }
        public Nullable<long> BorrowingId { get; set; }
        public int StatusId { get; set; }
        public System.DateTime SubmittedDateTime { get; set; }
        public Nullable<System.DateTime> ConfirmedDateTime { get; set; }
    }
}
