//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiVer1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VLMSMainDBEntities : DbContext
    {
        public VLMSMainDBEntities()
            : base("name=VLMSMainDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Borrowing> Borrowings { get; set; }
        public virtual DbSet<BorrowingRequest> BorrowingRequests { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<ItemCategory> ItemCategories { get; set; }
        public virtual DbSet<ItemProfilePhoto> ItemProfilePhotoes { get; set; }
        public virtual DbSet<JoinningRequest> JoinningRequests { get; set; }
        public virtual DbSet<Library> Libraries { get; set; }
        public virtual DbSet<Manuafactory> Manuafactories { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<Review> Reviews { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Transfer> Transfers { get; set; }
        public virtual DbSet<Warehouse> Warehouses { get; set; }
    }
}
